### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by dejury** [justbetter/laravel-akeneo-client#13]
Hi there,

I tried to get this package compatible with Laravel 11, but I keep seeing errors in the pipelines.
Can somebody please have a look if they can get it running?

In need for this in Laravel 11 ;)

Thanks!

**Comment by ramonrietdijk** [comment]
Hi @dejury,

Thanks for your contribution!

Seems like the `orchestra/testbench` dependency does not have a version in your pipeline. This can be fixed by adding it to the matrix include list like [here](https://github.com/justbetter/laravel-akeneo-client/pull/14/files#diff-2ef7216db6f1a266a49ce5b5f287f2c21884de37ad95b775f437e5b09ccffb94R18).

I've added support for Laravel 11 in version 1.4.0!

**Comment by dejury** [comment]
Thanks for the quick reply :)
